name: 'Test Download from S3'

on: [pull_request]

jobs:
  test-pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false --local
          poetry install --with test,lint,dev

      - name: Download from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc pull data/01_raw/cifar-10-python.tar.gz
          dvc pull data/06_models/cifar10_model.ckpt/trained_base/cifar10_model.ckpt

      - name: Run Kedro data_download pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          kedro run --pipeline data_download --env aws_download

      - name: Test with pytest
        run: |
          pytest
