loaders:
  train_loader:
    batch_size: 4
    shuffle: True
    num_workers: 4
  test_loader:
    batch_size: 4
    shuffle: False
    num_workers: 4

transforms:
  train_transforms:
    - ToTensor
    - Normalize:
        mean: (0.4914, 0.4822, 0.4465)
        std: (0.247, 0.243, 0.261)
    - AutoAugmentPolicy: cifar10
  test_transforms:
    - ToTensor
    - Normalize:
        mean: (0.4914, 0.4822, 0.4465)
        std: (0.247, 0.243, 0.261)
