trainer_params:
  accelerator: 'cpu'
  log_every_n_steps: 10
  val_check_interval: 0.2
  devices: 1
  max_epochs: 3

optimizer_params:
  type: Adam
  parameters:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0
